# Generated by Django 6.0.5 on 2026-06-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_bio_usuario_foto_perfil_usuario_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_grupo',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
